### PR TITLE
GH-329: (android) Fixes issue: Exif data lost on many cases

### LINKED ISSUE #329: Exif data lost when correctOrientation is true
The image I retrieve in the success callback has proper exif data if I set the options to:
```
 let options = {
    sourceType: Camera.PictureSourceType.CAMERA,
    destinationType: Camera.DestinationType.FILE_URI
};
```

Once I use `correctOrientation` (or quality, or targetHeight or targetWidth) in the options, the exif data is lost:
```
 let options = {
    correctOrientation: true,
    sourceType: Camera.PictureSourceType.CAMERA,
    destinationType: Camera.DestinationType.FILE_URI
};
```

### PR DESCRIPTION
**Pull request by AlvaroHerrero**
### Platforms affected
Android

### What does this PR do?
Reads the exif data from the file on these cases:
-When destType = DATA_URL
-When file is selected from gallery.
-When targetHeight or targetWidth is set, quality is not 100 or correctOrientation is true

### What testing has been done on this change?
Tested on two differente android devices.

### Checklist
- [ ] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [x] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [ ] Added automated test coverage as appropriate for this change.

---
closes #329

### CODE REVIEW

File: src/android/CameraLauncher.java [hunk 1]
```diff
@@ -994,6 +994,7 @@ private Bitmap getScaledAndRotatedBitmap(String imageUrl) throws IOException {
                         // read exifData of source
                         exifData = new ExifHelper();
                         exifData.createInFile(filePath);
+                        exif.readExifData();
```
Comment (janpio) [inline src/android/CameraLauncher.java]: Where is this variable used? If `this.correctOrientation` is true, it is overwritten again and then used to get the orientation, but otherwise?

File: src/android/CameraLauncher.java [hunk 2]
```diff
@@ -994,6 +994,7 @@ private Bitmap getScaledAndRotatedBitmap(String imageUrl) throws IOException {
                         // read exifData of source
                         exifData = new ExifHelper();
                         exifData.createInFile(filePath);
```
Comment (janpio) [inline src/android/CameraLauncher.java]: OT to your PR, but man is this a bad variable file. I read it as "create in file", but it actually means "create in(put)file".

File: src/android/CameraLauncher.java [hunk 3]
```diff
@@ -994,6 +994,7 @@ private Bitmap getScaledAndRotatedBitmap(String imageUrl) throws IOException {
...
+                        exifData.readExifData();
```
Comment (janpio) [inline src/android/CameraLauncher.java]: I still don't really understand how reading some data into a property/class variable of `exifData` influences the further execution of code. Can you explain?

**Comment by ddsky** [comment]
I have tested this and it works as intended. Voting for a pull of this fix.

**Comment by janpio** [comment]
(@ddsky You should be able to leave an actual "Approve" review in the "Files changed" tab - that will make it easier for us to spot the positive review. Thanks!)

**Comment by ddsky** [comment]
any news on when this will be merged?

**Comment by janpio** [comment]
You will learn about it here by an update to the PR being posted by GitHub. (If I am involved, it will now happen 2 minutes later as I had to open this notification, read your message and reply.)

**Comment by BorntraegerMarc** [comment]
Can I help in anyway to get this PR merged? It has been quite some time and it seems like everything is ok 🙂

**Comment by BorntraegerMarc** [comment]
thanks all for merging! Could someone tell me when the next version release is planned? 🙂

**Comment by janpio** [comment]
No, as there is not ETA for releases. Someone from the committer team will have to take the time to prepare the release (which means understanding all the PRs merged, giving them another round of testing, doing the actual release. this time probably also updating CI configuration as the last release was some time ago and new OS versions were released - which of course also have to be tested.)

**Comment by mirko77** [comment]
Exif metadata are not saved on iOS either (iOS 12) with the following settings:

```
camera_options = {
                                quality: 50,
                                sourceType: source_type,
                                destinationType: Camera.DestinationType.FILE_URI,
                                targetWidth: 1024,
                                targetHeight: 1024,
                                encodingType: Camera.EncodingType.JPEG,
                                correctOrientation: true
                            };

```

Is this issue related?

**Comment by AlvaroHerrero** [comment]
It should not. I just fixed the Java code for Android.

**Comment by mirko77** [comment]
I will have to open another issue then, could not find any existing one about EXIF data missing.
Works fine on Android though, and I do not have the PR in my code. Weird

**Comment by BorntraegerMarc** [comment]
@mirko77 EXIF data is working fine for us on iOS 12

**Comment by mirko77** [comment]
> @mirko77 EXIF data is working fine for us on iOS 12

@BorntraegerMarc I cannot figure it out. Even if I take a picture with the camera app and send it to me via Gmail, the image does not have any EXIF metadata in it. Any suggestions?

**Comment by chintan13** [comment]
I am also facing this issue. let me once you create special issue for it, so I can also follow progress on it.

**Comment by mirko77** [comment]
> I am also facing this issue. let me once you create special issue for it, so I can also follow progress on it.

Do you mean you cannot get the EXIF data in iOS as well?

**Comment by dlydiard** [comment]
i also do not get EXIF data on iOS when using the camera with:
  {
    quality: 85,
    sourceType: Camera.PictureSourceType.CAMERA,
    mediaType: Camera.MediaType.PICTURE,
    allowEdit: false,
    correctOrientation: true 
  }

**Comment by chintan13** [comment]
Yes in case of IOS  HEIC image format
sourceType = this.camera.PictureSourceType.PHOTOLIBRARY;
destinationType = this.camera.DestinationType.FILE_URI

We are loosing metadata from image.

**Comment by mirko77** [comment]
Has this issue been reported yet? @chintan13 @dlydiard

**Comment by chintan13** [comment]
no but there is open pr from last two years,
I suspect now that code might be much outdated.

**Comment by janpio** [comment]
Please open an issue @chintan13 and link to the PR - this will greatly improve the chance that the PR gets merged.

**Comment by ryaa** [comment]
> Has this issue been reported yet? @chintan13 @dlydiard

I added an issue for the problem with EXIF on iOS (see https://github.com/apache/cordova-plugin-camera/issues/524) and provided a potential fix (see https://github.com/apache/cordova-plugin-camera/pull/525)
