### PR TITLE
Bugfix issue 341 save to photo gallery - Fixes #341, fixes #577

### LINKED ISSUE #341: Save Photo To Album - Android (not tested on iOS)
When I use `saveToPhotoAlbum:  true;` it throws "Unable to obtain picture: Error capturing image.". When im not using `saveToPhotoAlbum`, it saves the picture to the cache, and removes it after a few days. I need the picture to be persistent.

### LINKED ISSUE #577: SaveToPhotoAlbum does not save image on Android
# Bug Report
When setting `saveToPhotoAlbum` to be `true` image is not saved

### What is expected to happen?
Image should be saved to photo album

### What does actually happen?
Image is not saved

## Information

Pretty straight forward - clicking on a button to open the camera, taking a picture, the picture is used in the app but does not appear in the gallery
Related to #341

### Command or Code

https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.Web/sources/application/directives/image-capture.directive.ts#L50L55

### Environment, Platform, Device
Android, both samsung 9 and xiomi redmi 4, 
App can be found here:
https://play.google.com/store/apps/details?id=il.org.osm.israelhiking&hl=en
Clicking the up-side-down drop on the right
Clicking a location on the map
Clicking on the camera to take a picture
Clicking OK in the camera app
The image is presented in the app but it is not stored in the gallery.

### Version information

Cordova 9.0
Cordova-plugin-camera 4.0.3

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

### PR DESCRIPTION
**Pull request by PieterVanPoyer**
### Platforms affected

- Android

### Motivation and Context

- Fixes #341
- Fixes #577

The saveToPhotoAlbum setting throws an exception while using the camera. (sourceType = CAMERA)
This results in a crash of the application. 
The first bug was reported in september 2018.
This PR only tries to solve the issue for the sourceType Camera.PictureSourceType.CAMERA, not for when the sourceType is PHOTOLIBRARY.
A reproduction of the issue can be done with https://github.com/PieterVanPoyer/cordova-camera-plugin-testing-app repo.

### Description

- saveToPhotoAlbum feature fixed by taken into count content - uri. (writeUncompressedImage method) ( see: apache#611 (comment) )
- make saveToPhotoAlbum future proof by using the MediaStore to insert the taken image
- made a method to calculate the compressFormat based on the encodingType (JPEG or PNG)
- layout of the performCrop method is adjusted
- removed unused rotate variable inside processResultFromGallery method
- added a GalleryPathVO (ValueObject) for more easy working with the path and imagename.
- add extra VO class to the plugin.xml

### Testing

I did run npm run test.
Tested on Android emulators from Android 5.1, 7, 10 and 11.
Tested on a real Samsung J7 device (Android 9), tested on a Samsung Galaxy tablet.

### Checklist

- [x] I've run the tests to see all new and existing tests pass
- [x] I added automated test coverage as appropriate for this change
- [x] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [x] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [x] I've updated the documentation if necessary

### CODE REVIEW

**Comment by PieterVanPoyer** [comment]
@erisu or @breautek can anybody review this PR, please?

**Comment by breautek** [comment]
Travis is failling on browser tests, and considering this PR changes nothing in the browser platform, I don't think it's a blocker. It seems to be a timeout issue, so I'll close/reopen this PR to retrigger travis. Maybe that's all it is.

I had a glance at this PR and I don't see anything wrong, but I would like to spend some time to actually test on a physical device, but I don't think I can do that this week.

**Review by breautek — APPROVED** [review]

**Comment by PieterVanPoyer** [comment]
@erisu Hey, I hate to disturb you, but can you find the time to review this PR. Kind regards.

**Comment by PieterVanPoyer** [comment]
@breautek Hey it seems like erisu can not find the time to review this PR, maybe just merge it to the master? Or maybe we should request another reviewer?
Kind regards.

**Comment by breautek** [comment]
I'll give a 1 week call out.

If there are no objections by October 16 I'll merge.

**Comment by PieterVanPoyer** [comment]
> I'll give a 1 week call out.
> 
> If there are no objections by October 16 I'll merge.

Sound like a great plan! Thanks.

File: src/android/CameraLauncher.java [hunk 1]
```diff
@@ -494,16 +494,18 @@ private void processResultFromCamera(int destType, Intent intent) throws IOExcep
...
-            galleryUri = Uri.fromFile(new File(getPicturesPath()));
+            GalleryPathVO galleryPathVO = getPicturesPath();
+            galleryUri = Uri.fromFile(new File(galleryPathVO.getGalleryPath()));
 
             if (this.allowEdit && this.croppedUri != null) {
                 writeUncompressedImage(croppedUri, galleryUri);
             } else {
-                Uri imageUri = this.imageUri;
-                writeUncompressedImage(imageUri, galleryUri);
+                if (Build.VERSION.SDK_INT <= Build.VERSION_CODES.P) { // Between LOLLIPOP_MR1 and P
```
Comment (breautek) [inline src/android/CameraLauncher.java:503]: I kinda forget android behaviour, can we double check that `Build.VERSION_CODES.P` is safe to use on devices that are API  < 28?

Ie: Android 5.1 simulator, with an app built with target API 29.

**Review by erisu — APPROVED** [review]

File: src/android/CameraLauncher.java (hunk 1 above)
Comment (PieterVanPoyer) [reply src/android/CameraLauncher.java:503]: Yes, this works.
- I dit test with target API 29, and 5.1 emulator. It works.

The Build.VERSION_CODES are compile-time constants that gets inlined in the generated bytecode. Because of that, the symbol does not need to be resolved at runtime.

Some additional context:
- I did also make the decision to use smaller or equal to Build.VERSION_CODES.P instead of smaller than Build.VERSION_CODES.Q . Because When you downscale the compile version to 28, it keeps compiling and working. 
- But you cannot compile with version 27. Becuase VERSION_CODES.P is not available in that sdk.

image

Comment (breautek) [reply src/android/CameraLauncher.java:503]: Ok, even though this normally would be the acceptable approach because Google Play enforces apps to be built with target SDK 28, (and soon to be forced for all apps to use API target 29)

Cordova is suppose to support enterprise environments where the play store is not involved in their process, and therefore they may use a lower target SDK than what Google demands. This means we can't actually use the `VERSION_CODES` constants unless if they are introduced in/before our min sdk level. So I guess for now the solution to this is to change `Build.VERSION_CODES.P` to a hard-code numerical `28`.

This isn't documented in the Cordova docs, I'm requesting the actual minimum target API we support to be defined so that this can actually be documented.

Comment (PieterVanPoyer) [reply src/android/CameraLauncher.java:503]: @breautek 

I digged a little deeper.
When I change the Build.VERSION_CODES_P to the numerical 28 , I am able to compile and run it with the defaultCompileSdkVersion starting from 22 and higher.
So I changed the code to the 28 number.

image

But is it really necessary to be able to compile with the sdk version equal to 22?

Kind regards
Pieter

**Review by breautek — APPROVED** [review]

File: src/android/CameraLauncher.java (hunk 1 above)
Comment (breautek) [reply src/android/CameraLauncher.java]: > But is it really necessary to be able to compile with the sdk version equal to 22?

My personal opinion is no.... but I think that's what our min requirement is going to be. I'm about to write a new thread in the dev mail to see if the community can come to a consensus and so that we can document what Cordova supports for enterprise users. I'm assuming the consensus will be "whatever what the min sdk version is", which is currently 22.

Obviously this only applies to people who aren't publishing to the google play store.

**Comment by breautek** [comment]
Travis failures are unrelated to this PR. Merging now. Thank you @PieterVanPoyer for your time and effort in preparing this PR.
